Documentation request for Smart Message Account
signalive/documentation pull request #1
Opened 2020-11-05 10:56 UTC by selmanozturk

[ML-285] Documentation request for Smart Message Account

2020-11-05 10:58 UTC, AlphanB approved these changes

2020-11-05 11:21 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        .catch(err => {error: true});
buradaki {error:true} kafa karıştırabilir, aşağıda hiç kullanmıyoruz

2020-11-05 11:28 UTC, ilgaz requested changes

2020-11-05 11:28 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        const movieData = await getData();
Buradaki try..catch'i kaldırıp `await getData()`'nın sonuna catch ekleyip orada helpers.raiseError() yapmak nasıl olur? (Implementasyon fikri bu arada, change request değil)

2020-11-05 11:28 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/postman-api/index.html
> +            //error: true,
buradaki `error: true` kısmını anlatan bir comment bloğu nasıl olur?

Yukarıdaki `getData()`'yı kullanıp burada error gönderdiğinizde VQ içerisinde kontrol ederek `helpers.raiseError` ile açılmasını engelleyebilirsiniz gibi desek okay

2020-11-05 11:28 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/postman-api/index.html
> +            //error: true,
Ayrıca bunun corresponding VQ dökümanında da onu check eden yer olursa harika

2020-11-08 20:39 UTC, selmanozturk commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        .catch(err => {error: true});
duzenlendi @ilgaz

2020-11-08 20:39 UTC, selmanozturk commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        const movieData = await getData();
burayi biraz duzenledim, daha okunur gozukuyor

2020-11-08 20:40 UTC, selmanozturk commented on VQ/dynamic-data-references/scripts/postman-api/index.html
> +            //error: true,
duzenlendi @ilgaz

2020-11-09 11:07 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        .catch(err => {error: true});
LGTM

2020-11-09 11:07 UTC, ilgaz commented on VQ/dynamic-data-references/scripts/ajax-request/background-service.js
> +        const movieData = await getData();
nice, LGTM

2020-11-09 20:26 UTC, merged